#!/usr/bin/env python
# encoding: utf-8

# Just a Simple HTTP Server to serve the On Air Light page

import SimpleHTTPServer, SocketServer, os, sys

PORT = 8000

os.chdir("srv")
Handler = SimpleHTTPServer.SimpleHTTPRequestHandler
httpd = SocketServer.TCPServer(("", PORT), Handler)
print("[+] Started onair at port ", PORT)
httpd.serve_forever()
